"""Re-export AST parser constants from language-specific modules.

This module provides convenient access to constants from all supported languages.
"""

# Re-export Python constants
from app.ast.languages.constants.python_constants import (
    PYTHON_CALL_TYPES,
    PYTHON_DEFINITION_TYPES,
    PYTHON_IMPORT_TYPES,
    PYTHON_NODE_TYPE_MAPPING,
    PYTHON_PARENT_DEFINITION_TYPES,
    PYTHON_IDENTIFIER_TYPES,
    PYTHON_COMPLEX_NAME_TYPES,
    PYTHON_DECORATOR_KEYWORDS,
    PYTHON_ASYNC_KEYWORDS,
    PYTHON_COMPREHENSION_TYPES,
)

# Re-export TypeScript constants
from app.ast.languages.constants.typescript_constants import (
    TYPESCRIPT_CALL_TYPES,
    TYPESCRIPT_DEFINITION_TYPES,
    TYPESCRIPT_IMPORT_TYPES,
    TYPESCRIPT_NODE_TYPE_MAPPING,
    TYPESCRIPT_PARENT_DEFINITION_TYPES,
    TYPESCRIPT_IDENTIFIER_TYPES,
    TYPESCRIPT_COMPLEX_NAME_TYPES,
    TYPESCRIPT_ACCESS_MODIFIERS,
    TYPESCRIPT_TYPE_KEYWORDS,
    TYPESCRIPT_GENERIC_KEYWORDS,
)

# Re-export JavaScript constants
from app.ast.languages.constants.javascript_constants import (
    JAVASCRIPT_CALL_TYPES,
    JAVASCRIPT_DEFINITION_TYPES,
    JAVASCRIPT_IMPORT_TYPES,
    JAVASCRIPT_NODE_TYPE_MAPPING,
    JAVASCRIPT_PARENT_DEFINITION_TYPES,
    JAVASCRIPT_IDENTIFIER_TYPES,
    JAVASCRIPT_COMPLEX_NAME_TYPES,
    JAVASCRIPT_CALLBACK_PATTERNS,
    JAVASCRIPT_GENERATOR_KEYWORDS,
    JAVASCRIPT_CLOSURE_PATTERNS,
)

# Legacy constants for backward compatibility
DEFINITION_TYPES = (
    PYTHON_DEFINITION_TYPES | TYPESCRIPT_DEFINITION_TYPES | JAVASCRIPT_DEFINITION_TYPES
)
CALL_TYPES = PYTHON_CALL_TYPES | TYPESCRIPT_CALL_TYPES | JAVASCRIPT_CALL_TYPES
IMPORT_TYPES = PYTHON_IMPORT_TYPES | TYPESCRIPT_IMPORT_TYPES | JAVASCRIPT_IMPORT_TYPES

# Combined node type mapping
NODE_TYPE_MAPPING = {
    **PYTHON_NODE_TYPE_MAPPING,
    **TYPESCRIPT_NODE_TYPE_MAPPING,
    **JAVASCRIPT_NODE_TYPE_MAPPING,
}

PARENT_DEFINITION_TYPES = (
    PYTHON_PARENT_DEFINITION_TYPES
    | TYPESCRIPT_PARENT_DEFINITION_TYPES
    | JAVASCRIPT_PARENT_DEFINITION_TYPES
)

IDENTIFIER_TYPES = (
    PYTHON_IDENTIFIER_TYPES | TYPESCRIPT_IDENTIFIER_TYPES | JAVASCRIPT_IDENTIFIER_TYPES
)

COMPLEX_NAME_TYPES = (
    PYTHON_COMPLEX_NAME_TYPES
    | TYPESCRIPT_COMPLEX_NAME_TYPES
    | JAVASCRIPT_COMPLEX_NAME_TYPES
)
