[project]
name = "code-analyzer-parser"
version = "0.1.0"
description = "Parse AST of code and build graph with it"
requires-python = ">=3.13"
dependencies = [
    "tree-sitter>=0.25.2",
    "tree-sitter-javascript>=0.25.0",
    "tree-sitter-python>=0.25.0",
]
