[project]
name = "code-analyzer-core"
version = "0.2.0"
description = "LLM-powered code analysis and GraphRAG service"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.0",
    "code-analyzer-parser",
    "code-analyzer-graph",
    "langchain>=0.3.0",
    "langchain-core>=0.3.0",
    "langchain-community>=0.3.0",
    "langgraph>=0.2.0",
    "langchain-google-genai>=2.0.0",
    "sentence-transformers>=2.2.0",
    "torch>=2.0.0",
]

[tool.uv.sources]
code-analyzer-parser = { path = "../parser" }
code-analyzer-graph = { path = "../graph" }
