[project]
name = "code-analyzer-core"
version = "0.2.0"
description = "LLM-powered code analysis and GraphRAG service"
requires-python = ">=3.13"
dependencies = [
    "neo4j>=6.0.2",
    "pydantic>=2.12.0",
    "code-analyzer-parser",
    "code-analyzer-graph",
    "langchain>=1.0.1",
    "langgraph>=1.0.0",
    "langchain-google-genai>=3.0.0",
]

[tool.uv.sources]
code-analyzer-parser = { path = "../parser" }
code-analyzer-graph = { path = "../graph" }
