[project]
name = "code-analyzer-core"
version = "0.1.0"
description = "Interact with LLM and control db"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.0a4",
]

[tool.uv.sources]
ast-parser = { path = "../parser" }
