"""상수 정의

Core 패키지에서 사용하는 상수들을 중앙화하여 관리합니다.
"""

# 임베딩 배치 처리
DEFAULT_EMBEDDING_BATCH_SIZE = 32

# 검색 관련
DEFAULT_RELATED_NODES_LIMIT = 5
DEFAULT_CONTEXT_DEPTH = 2
DEFAULT_SIMILARITY_THRESHOLD = 0.7
DEFAULT_MAX_RESULTS = 10

# Neo4j 배치 처리
DEFAULT_NEO4J_BATCH_SIZE = 500
